---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-microservice
  labels:
    app: java-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-microservice
  template:
    metadata:
      labels:
        app: java-microservice
    spec:
      containers:
      - name: java-microservice
        image: rafaelportela/springboot-java-microservice:1.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: java-microservice
spec:
  selector:
    app: java-microservice
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8080
